-- Let's generate a report showing each customer’s name, along with
-- their city, the total number of rentals, and the total payment amount

-- Grouping on the customer’s first and last names --
SELECT 
    c.first_name,
    c.last_name,
    ct.city,
    SUM(p.amount) AS tot_payments,
    COUNT(*) AS tot_rentals
FROM
    payment AS p
        INNER JOIN
    customer AS c ON p.customer_id = c.customer_id
        INNER JOIN
    address AS a ON c.address_id = a.address_id
        INNER JOIN
    city AS ct ON a.city_id = ct.city_id
GROUP BY c.first_name , c.last_name;

-- Let's separate out the task of generating the groups into
-- a subquery and then join the other three tables to the table generated by 
-- the subquery to achieve the desired end result.

SELECT 
    customer_id,
    COUNT(*) AS tot_rentals,
    SUM(amount) AS tot_payments
FROM
    payment
GROUP BY customer_id;

-- The next query joins the previous data set to the other three tables:
SELECT 
    c.first_name,
    c.last_name,
    ct.city,
    p.tot_payments,
    p.tot_rentals
FROM
    (SELECT 
        customer_id,
            COUNT(*) AS tot_rentals,
            SUM(amount) AS tot_payments
    FROM
        payment
    GROUP BY customer_id) AS p
        INNER JOIN
    customer AS c ON p.customer_id = c.customer_id
        INNER JOIN
    address AS a ON c.address_id = a.address_id
        INNER JOIN
    city AS ct ON a.city_id = ct.city_id;